### ISSUE TITLE
relative_url for all internal urls

### ISSUE THREAD

**Issue by mdlincoln** [FrankensteinVariorum/viewer#1]
to make build agnostic to final deployment url

**Comment by mdlincoln** [comment]
Bill set this up to build scss via gulp/JS instead of through Jekyll, so it's difficult to swap out some of the hardcoded asset urls for `backround-image` properties. I'm going to experiment with ripping out the js-based scss build and lettin gjekyll do it instead, hopefully this solves it and lets us have a more freely-configurable deployment. If it looks like too much trouble, then I'll just hardcode the `/fv-jekyll` baseurl for github display.

**Comment by mdlincoln** [comment]
Hey @raffazizzi, I've started to experiment with the build here. It's hacky but it nearly works - except paths to some assets are messed up because the deployed site expects the base url `/viewer` to be appended to everything, and some of the links defined in the react app are missing it, such as the links to the manicule assets, etc.

For example, it's looking for the SGA logo at `http://localhost:4000/static/media/sgalogo.151f80c9.png` (on my local build etc.) whereas the deployed static assets are at `http://localhost:4000/viewer/static/media/sgalogo.151f80c9.png`

Here's the build process:

1. Run `npm run build` in the react app repo.
2. Copy the `build` folder into THIS repo at `_source/viewer/build`
3. Run `npm install` and `bundle install` in THIS repo to get the node and Ruby packages, then `gulp buildLocal`. This runs VERY hacky code from Agile [described here](https://github.com/FrankensteinVariorum/viewer/blob/db359d3101be112da70ad87864c6136f56d7384e/gulpfile.js#L311-L359) to mvoe the react app's assets into the right place in the Jekyll hierarchy.

This is where things go off the rails. Bill's gulpfile includes code that rewrites React paths in the `index.html` file to `/static` to instead point to `/viewer/viewer/static`. This probably needs to happen for other places where asset paths are encoded in the react app. 

**We can't serve assets from `/static`, the base url must start with `/viewer` - any file in the root of the Jekyll site will start with the baseurl `/viewer` on the deployed site.**

Hope this explanation makes sense. Any ideas how we might best do this? I think we're very close, otherwise...

**Comment by raffazizzi** [comment]
@mdlincoln I just tried this locally and the images show up for me. BUT the CSS seems to be incomplete, e.g. the SGA logo shows up huge. What could be causing this inconsistency? I followed your instructions and then ran Jekyll with `bundle exec jekyll serve --watch --config _config.yml,_local_config.yml`. Serving the site statically from `_site` yelds the same result.

![Screenshot from 2019-12-11 16-54-10](https://user-images.githubusercontent.com/144770/70663730-f1dfa900-1c36-11ea-8f36-e4ff28db0c39.png)

**Comment by mdlincoln** [comment]
@raffazizzi hm, you may try running it just with `--config _config.yml`. This will serve the site at `http://localhost:4000/viewer/` (the `_config_local.yml` serves it without the `/viewer` baseurl.) Depending at which stage you've injected `/viewer` into your code, the `_local_config.yml` may be causing a mixup.

**Comment by raffazizzi** [comment]
@mdlincoln when I do that, the react app doesn't load. It seems that it looks for it at `/viewer/static/js/`. I'm feeling a bit lost...

**Comment by mdlincoln** [comment]
@raffazizzi I apologize, it's difficult to explain because the system Agile put together is convoluted 😦  Have time for a zoom call this afternoon? Might help if I can share my screen and talk it through out loud

**Comment by mdlincoln** [comment]
@raffazizzi just pushed the changes we discussed over zoom. Plumbing the SCSS now

**Comment by mdlincoln** [comment]
You'll want to edit either _general.sass or _viewer.sass in https://github.com/FrankensteinVariorum/viewer/tree/master/_sass/c_local/40_components/viewer - when jekyll builds, it will process these files and regenerate the CSS appropriately. Just tested it against the SGA logo image and it works.

**Comment by raffazizzi** [comment]
Done! And I was able to set up a production path in the React repository, so I also removed the path rewrite in the gulpfile as that's no longer needed.
Please give it another test to make sure this all works on your end, too!

**Comment by mdlincoln** [comment]
Great, i've got the images coming through properly now.

I'm seeing some annotation display issues on my end, but will open a different ticket for that.
