### ISSUE TITLE
Debug the /docs build process

### ISSUE THREAD

**Issue by mdlincoln** [FrankensteinVariorum/viewer#9]
Tried to do a test deploy all the way up to github pages via `gulp build` and it's not working - will investigate more in the morning.

**Comment by mdlincoln** [comment]
(have reverted the broken commit)

**Comment by mdlincoln** [comment]
apparently github pages has been experiencing intermittent page build failures today: https://twitter.com/githubstatus/status/1205541379235106817

Some simple updates to the about page that I committed are not showing up on the live site yet, so the problem may not lie in the viewer at all. Will keep monitoring.

**Comment by Rikkm** [comment]
Elisa just noticed the viewer is not working (12/13/2019 18:30-ish)
I went through the code and the fault seems to involve "missing" JS files.
I can't troubleshoot the script well enough to verify other than those JS are not where the viewer seems to expect them to be.
